#!/bin/bash

echo "=== SSH Server Deployment to Raspberry Pi ==="
echo ""
echo "Option 1: Clone and build directly on Pi (Recommended)"
echo "=================================================="
echo "1. SSH into your Raspberry Pi:"
echo "   ssh pi@your-raspberry-pi-ip"
echo ""
echo "2. Install Java 21+ if not already installed:"
echo "   sudo apt update"
echo "   sudo apt install openjdk-21-jdk"
echo ""
echo "3. Clone the repository:"
echo "   git clone https://github.com/your-username/ssh.git"
echo "   cd ssh"
echo ""
echo "4. Build the server-only JAR:"
echo "   ./gradlew serverPiJar"
echo ""
echo "5. Run the server:"
echo "   java -jar app/build/libs/ssh-server-pi-all.jar"
echo ""
echo ""
echo "Option 2: Copy pre-built JAR (Alternative)"
echo "=========================================="
echo "1. Build locally: ./build-server-pi.sh"
echo "2. Copy to Pi: scp app/build/libs/ssh-server-pi-all.jar pi@pi-ip:/home/pi/"
echo "3. Copy data: scp -r data/ pi@pi-ip:/home/pi/"
echo "4. Run on Pi: java -jar ssh-server-pi-all.jar"
echo ""
echo "Note: Option 1 is better as it ensures the Pi has all build tools"
echo "and can rebuild if needed." 